import { Document } from './document.types';

const now = new Date();
const ts = (daysAgo: number) =>
  new Date(now.getTime() - daysAgo * 86_400_000).toISOString();

export const SEED_DOCUMENTS: Document[] = [
  {
    documentId: 'doc-001',
    title: 'IAM Governance Policy',
    category: 'policy',
    owner: 'admin@idvize.io',
    tags: ['governance', 'iam', 'policy'],
    status: 'published',
    currentVersion: 3,
    versions: [
      {
        version: 1,
        content: `# IAM Governance Policy\n\n## Purpose\nThis policy establishes the governance framework for Identity and Access Management.\n\n## Scope\nApplies to all systems, users, and third-party integrations managed by IDVIZE.\n\n## Principles\n1. Least privilege access\n2. Separation of duties\n3. Regular access reviews\n4. Audit logging for all access events`,
        changedBy: 'admin@idvize.io',
        changedAt: ts(30),
        changeNote: 'Initial draft',
      },
      {
        version: 2,
        content: `# IAM Governance Policy\n\n## Purpose\nThis policy establishes the governance framework for Identity and Access Management.\n\n## Scope\nApplies to all systems, users, and third-party integrations managed by IDVIZE.\n\n## Principles\n1. Least privilege access\n2. Separation of duties\n3. Regular access reviews (quarterly minimum)\n4. Audit logging for all access events\n5. MFA required for privileged accounts`,
        changedBy: 'admin@idvize.io',
        changedAt: ts(15),
        changeNote: 'Added MFA requirement for privileged accounts',
      },
      {
        version: 3,
        content: `# IAM Governance Policy v1.3\n\n## Purpose\nThis policy establishes the governance framework for Identity and Access Management across all IDVIZE-managed environments.\n\n## Scope\nApplies to all systems, users, service accounts, and third-party integrations managed by IDVIZE.\n\n## Principles\n1. **Least Privilege**: Grant minimum necessary permissions\n2. **Separation of Duties**: No single user controls entire workflows\n3. **Regular Access Reviews**: Quarterly for standard users, monthly for privileged\n4. **Audit Logging**: All access events logged and retained for 12 months\n5. **MFA Required**: All privileged accounts must enrol in MFA\n6. **Zero-Trust**: Never trust, always verify\n\n## Enforcement\nViolations are subject to disciplinary action per HR policy.`,
        changedBy: 'manager@idvize.io',
        changedAt: ts(5),
        changeNote: 'Added zero-trust principle and enforcement clause',
      },
    ],
    reviews: [
      {
        reviewId: 'rev-001',
        documentId: 'doc-001',
        version: 3,
        reviewedBy: 'manager@idvize.io',
        reviewedAt: ts(4),
        outcome: 'approved',
        comments: 'Approved after adding enforcement clause.',
      },
    ],
    createdAt: ts(30),
    updatedAt: ts(5),
    publishedAt: ts(4),
  },
  {
    documentId: 'doc-002',
    title: 'Privileged Access Management Runbook',
    category: 'runbook',
    owner: 'admin@idvize.io',
    tags: ['pam', 'privileged', 'runbook', 'vault'],
    status: 'in_review',
    currentVersion: 2,
    versions: [
      {
        version: 1,
        content: `# PAM Runbook\n\n## Overview\nStep-by-step procedures for managing privileged accounts in the IDVIZE vault.\n\n## Credential Request Flow\n1. Submit request via /security/credentials/request\n2. Manager approves within 4 hours\n3. Credential is auto-rotated after 8 hours\n4. All access logged to audit trail`,
        changedBy: 'admin@idvize.io',
        changedAt: ts(20),
        changeNote: 'Initial runbook',
      },
      {
        version: 2,
        content: `# PAM Runbook v1.2\n\n## Overview\nStep-by-step procedures for managing privileged accounts in the IDVIZE vault.\n\n## Credential Request Flow\n1. Submit request via /security/credentials/request with justification\n2. Manager approves within 4 hours (auto-rejected after 8 hours)\n3. Credential delivered via vault reference — never in plaintext\n4. Auto-rotated after checkout TTL expires\n5. All access logged to immutable audit trail\n\n## Emergency Break-Glass\n- Break-glass accounts: bg-admin-001, bg-admin-002\n- Requires dual approval\n- Triggers automated security alert\n\n## Rotation Schedule\n| Account Type | Rotation Frequency |\n|---|---|\n| Service accounts | 90 days |\n| Admin accounts | 30 days |\n| API keys | 60 days |`,
        changedBy: 'admin@idvize.io',
        changedAt: ts(3),
        changeNote: 'Added emergency break-glass procedure and rotation schedule',
      },
    ],
    reviews: [
      {
        reviewId: 'rev-002',
        documentId: 'doc-002',
        version: 2,
        reviewedBy: 'manager@idvize.io',
        reviewedAt: ts(2),
        outcome: 'pending',
        comments: 'Reviewing break-glass procedures.',
      },
    ],
    createdAt: ts(20),
    updatedAt: ts(3),
  },
  {
    documentId: 'doc-003',
    title: 'Access Review Procedure',
    category: 'procedure',
    owner: 'manager@idvize.io',
    tags: ['access-review', 'compliance', 'procedure'],
    status: 'draft',
    currentVersion: 1,
    versions: [
      {
        version: 1,
        content: `# Access Review Procedure\n\n## Objective\nEnsure all user access is reviewed and certified quarterly.\n\n## Steps\n1. Generate access report from IDVIZE\n2. Distribute to managers for certification\n3. Managers approve or revoke within 2 weeks\n4. Revoke access for all uncertified accounts\n5. Archive results for audit trail\n\n## [TODO: Add escalation path for unresponsive managers]`,
        changedBy: 'manager@idvize.io',
        changedAt: ts(7),
        changeNote: 'Initial draft — incomplete',
      },
    ],
    reviews: [],
    createdAt: ts(7),
    updatedAt: ts(7),
  },
  {
    documentId: 'doc-004',
    title: 'SSO Integration Architecture',
    category: 'architecture',
    owner: 'admin@idvize.io',
    tags: ['sso', 'oidc', 'architecture', 'integration'],
    status: 'published',
    currentVersion: 1,
    versions: [
      {
        version: 1,
        content: `# SSO Integration Architecture\n\n## Overview\nDescribes the OIDC/SAML integration architecture between IDVIZE and connected applications.\n\n## Authentication Flow\n\`\`\`\nUser → App → IDVIZE /auth/token → JWT → App grants access\n\`\`\`\n\n## Supported Protocols\n- **OIDC**: Primary protocol for modern applications\n- **SAML 2.0**: Legacy enterprise apps (Phase 2)\n\n## Token Lifecycle\n| Token Type | TTL | Rotation |\n|---|---|---|\n| Access token | 15 min | On expiry |\n| Refresh token | 7 days | On use |\n\n## Connected Applications\nSee CMDB for full application inventory.`,
        changedBy: 'admin@idvize.io',
        changedAt: ts(45),
        changeNote: 'Architecture document',
      },
    ],
    reviews: [
      {
        reviewId: 'rev-003',
        documentId: 'doc-004',
        version: 1,
        reviewedBy: 'manager@idvize.io',
        reviewedAt: ts(44),
        outcome: 'approved',
        comments: 'Architecture approved.',
      },
    ],
    createdAt: ts(45),
    updatedAt: ts(45),
    publishedAt: ts(44),
  },
  {
    documentId: 'doc-005',
    title: 'Vendor Onboarding Standard',
    category: 'standard',
    owner: 'manager@idvize.io',
    tags: ['vendor', 'onboarding', 'standard', 'security'],
    status: 'archived',
    currentVersion: 2,
    versions: [
      {
        version: 1,
        content: `# Vendor Onboarding Standard\n\nInitial requirements for vendor identity integration.`,
        changedBy: 'admin@idvize.io',
        changedAt: ts(90),
        changeNote: 'Initial version',
      },
      {
        version: 2,
        content: `# Vendor Onboarding Standard v2\n\nUpdated for new SCIM 2.0 integration requirements.`,
        changedBy: 'admin@idvize.io',
        changedAt: ts(60),
        changeNote: 'SCIM 2.0 update',
      },
    ],
    reviews: [],
    createdAt: ts(90),
    updatedAt: ts(60),
    archivedAt: ts(10),
  },
];
