/**
 * Demo seed data for Module 5 — Cost & Vendor Intelligence
 * Represents a mid-size enterprise IAM program (~$4.2M annual spend)
 */
import { v4 as uuidv4 } from 'uuid';
import { Vendor, Contract, PersonCost } from './cost.types';

// ── Vendors ───────────────────────────────────────────────────────────────────

export const SEED_VENDORS: Vendor[] = [
  // IAM Platforms
  {
    vendorId: 'v-sailpoint',
    name: 'SailPoint',
    type: 'iam_platform',
    category: 'IGA',
    supportedStandards: ['SCIM', 'REST', 'SAML'],
    integrationComplexity: 'standard',
    apiMaturity: 4,
    documentationQuality: 4,
    marketPresence: 'dominant',
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    vendorId: 'v-entra',
    name: 'Microsoft Entra ID',
    type: 'iam_platform',
    category: 'AM',
    supportedStandards: ['SAML', 'OIDC', 'SCIM', 'REST'],
    integrationComplexity: 'native',
    apiMaturity: 5,
    documentationQuality: 5,
    marketPresence: 'dominant',
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    vendorId: 'v-cyberark',
    name: 'CyberArk',
    type: 'iam_platform',
    category: 'PAM',
    supportedStandards: ['REST'],
    integrationComplexity: 'standard',
    apiMaturity: 4,
    documentationQuality: 4,
    marketPresence: 'dominant',
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    vendorId: 'v-okta',
    name: 'Okta',
    type: 'iam_platform',
    category: 'CIAM/AM',
    supportedStandards: ['SAML', 'OIDC', 'SCIM', 'REST'],
    integrationComplexity: 'native',
    apiMaturity: 5,
    documentationQuality: 5,
    marketPresence: 'dominant',
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // Application Vendors
  {
    vendorId: 'v-sap',
    name: 'SAP',
    type: 'application',
    category: 'ERP',
    supportedStandards: ['SAML', 'REST'],
    integrationComplexity: 'custom',
    apiMaturity: 3,
    documentationQuality: 3,
    marketPresence: 'dominant',
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    vendorId: 'v-salesforce',
    name: 'Salesforce',
    type: 'application',
    category: 'CRM',
    supportedStandards: ['SAML', 'OIDC', 'SCIM', 'REST'],
    integrationComplexity: 'native',
    apiMaturity: 5,
    documentationQuality: 5,
    marketPresence: 'dominant',
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    vendorId: 'v-atlassian',
    name: 'Atlassian',
    type: 'application',
    category: 'ITSM',
    supportedStandards: ['SAML', 'OIDC', 'SCIM'],
    integrationComplexity: 'standard',
    apiMaturity: 4,
    documentationQuality: 4,
    marketPresence: 'major',
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    vendorId: 'v-internal-legacy',
    name: 'Internal / Legacy',
    type: 'application',
    category: 'Custom/Legacy',
    supportedStandards: ['NONE'],
    integrationComplexity: 'manual',
    apiMaturity: 1,
    documentationQuality: 1,
    marketPresence: 'legacy',
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    vendorId: 'v-github',
    name: 'GitHub',
    type: 'application',
    category: 'DevTools',
    supportedStandards: ['SAML', 'SCIM', 'REST'],
    integrationComplexity: 'standard',
    apiMaturity: 5,
    documentationQuality: 5,
    marketPresence: 'dominant',
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // Implementation Partners
  {
    vendorId: 'v-cdw',
    name: 'CDW (IAM Practice)',
    type: 'implementation_partner',
    category: 'System Integrator',
    supportedStandards: ['SAML', 'OIDC', 'SCIM', 'REST'],
    integrationComplexity: 'standard',
    apiMaturity: 3,
    documentationQuality: 3,
    marketPresence: 'major',
    notes: 'Primary SI for SailPoint implementations',
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    vendorId: 'v-accenture',
    name: 'Accenture Security',
    type: 'implementation_partner',
    category: 'System Integrator',
    supportedStandards: ['SAML', 'OIDC', 'SCIM', 'REST', 'LDAP'],
    integrationComplexity: 'custom',
    apiMaturity: 4,
    documentationQuality: 3,
    marketPresence: 'dominant',
    notes: 'Engaged for CyberArk rollout and enterprise transformation',
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // Staff Augmentation
  {
    vendorId: 'v-infosys',
    name: 'Infosys BPM (IAM Offshore)',
    type: 'staff_augmentation',
    category: 'Offshore Managed Service',
    supportedStandards: ['SAML', 'SCIM', 'REST'],
    integrationComplexity: 'standard',
    apiMaturity: 3,
    documentationQuality: 2,
    marketPresence: 'major',
    notes: 'Handles L1/L2 IAM operations and SailPoint administration',
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    vendorId: 'v-staffing-us',
    name: 'TechServ Staffing (US Contractors)',
    type: 'staff_augmentation',
    category: 'Contractor Agency',
    supportedStandards: [],
    integrationComplexity: 'standard',
    apiMaturity: 3,
    documentationQuality: 2,
    marketPresence: 'niche',
    notes: 'Provides CyberArk and Entra contract engineers',
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
];

// ── Contracts ─────────────────────────────────────────────────────────────────

export const SEED_CONTRACTS: Contract[] = [
  // IAM Platforms
  {
    contractId: 'c-sailpoint-license',
    vendorId: 'v-sailpoint',
    vendorName: 'SailPoint',
    serviceType: 'saas_subscription',
    description: 'SailPoint IdentityNow — Enterprise License (10,000 identities)',
    annualCost: 480000,
    currency: 'USD',
    startDate: '2024-01-01',
    endDate: '2026-12-31',
    autoRenew: true,
    status: 'active',
    owner: 'CISO Office',
    tags: ['iga', 'iam-platform', 'core'],
    linkedPlatforms: ['SailPoint'],
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    contractId: 'c-sailpoint-support',
    vendorId: 'v-sailpoint',
    vendorName: 'SailPoint',
    serviceType: 'support_maintenance',
    description: 'SailPoint Premier Support — 24x7',
    annualCost: 72000,
    currency: 'USD',
    startDate: '2024-01-01',
    endDate: '2026-12-31',
    autoRenew: true,
    status: 'active',
    owner: 'IAM Team',
    tags: ['support', 'iga'],
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    contractId: 'c-entra-e5',
    vendorId: 'v-entra',
    vendorName: 'Microsoft Entra ID',
    serviceType: 'saas_subscription',
    description: 'Microsoft Entra ID P2 (bundled in M365 E5) — 4,200 seats',
    annualCost: 252000,
    currency: 'USD',
    startDate: '2023-07-01',
    endDate: '2025-06-30',
    autoRenew: true,
    status: 'active',
    owner: 'IT Operations',
    tags: ['am', 'mfa', 'conditional-access', 'iam-platform'],
    linkedPlatforms: ['Entra'],
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    contractId: 'c-cyberark-pam',
    vendorId: 'v-cyberark',
    vendorName: 'CyberArk',
    serviceType: 'saas_subscription',
    description: 'CyberArk Privilege Cloud — 500 privileged accounts',
    annualCost: 320000,
    currency: 'USD',
    startDate: '2024-06-01',
    endDate: '2027-05-31',
    autoRenew: false,
    status: 'active',
    owner: 'Security Operations',
    tags: ['pam', 'iam-platform', 'core'],
    linkedPlatforms: ['CyberArk'],
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    contractId: 'c-okta-ciam',
    vendorId: 'v-okta',
    vendorName: 'Okta',
    serviceType: 'saas_subscription',
    description: 'Okta Customer Identity Cloud — 500,000 MAUs',
    annualCost: 180000,
    currency: 'USD',
    startDate: '2025-01-01',
    endDate: '2026-12-31',
    autoRenew: true,
    status: 'active',
    owner: 'Digital Team',
    tags: ['ciam', 'iam-platform'],
    linkedPlatforms: ['Okta'],
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // Implementation Partners
  {
    contractId: 'c-cdw-sailpoint-impl',
    vendorId: 'v-cdw',
    vendorName: 'CDW (IAM Practice)',
    serviceType: 'professional_services',
    description: 'SailPoint IdentityNow implementation — Phase 2 (30 app onboardings)',
    annualCost: 360000,
    currency: 'USD',
    startDate: '2025-03-01',
    endDate: '2026-02-28',
    autoRenew: false,
    status: 'active',
    owner: 'IAM Programme Manager',
    tags: ['implementation', 'sailpoint', 'app-onboarding'],
    linkedPlatforms: ['SailPoint'],
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    contractId: 'c-accenture-cyberark',
    vendorId: 'v-accenture',
    vendorName: 'Accenture Security',
    serviceType: 'professional_services',
    description: 'CyberArk enterprise rollout — design, deployment, and knowledge transfer',
    annualCost: 520000,
    currency: 'USD',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    autoRenew: false,
    status: 'active',
    owner: 'CISO Office',
    tags: ['implementation', 'cyberark', 'pam'],
    linkedPlatforms: ['CyberArk'],
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },

  // Staff Augmentation
  {
    contractId: 'c-infosys-ops',
    vendorId: 'v-infosys',
    vendorName: 'Infosys BPM (IAM Offshore)',
    serviceType: 'managed_service',
    description: 'IAM Operations MSP — SailPoint admin, access reviews, helpdesk L1/L2 (8 FTE offshore)',
    annualCost: 320000,
    currency: 'USD',
    startDate: '2023-01-01',
    endDate: '2025-12-31',
    autoRenew: true,
    status: 'active',
    owner: 'IAM Manager',
    tags: ['operations', 'msp', 'offshore', 'sailpoint'],
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    contractId: 'c-techserv-contractors',
    vendorId: 'v-staffing-us',
    vendorName: 'TechServ Staffing (US Contractors)',
    serviceType: 'staff_augmentation',
    description: '3x US contract engineers — CyberArk (1) + Entra (1) + SailPoint (1)',
    annualCost: 450000,
    currency: 'USD',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    autoRenew: false,
    status: 'active',
    owner: 'IAM Manager',
    tags: ['contractors', 'cyberark', 'entra', 'sailpoint'],
    createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
  },
];

// ── People Costs ──────────────────────────────────────────────────────────────

export const SEED_PEOPLE: PersonCost[] = [
  // Internal FTEs
  { personId: 'p-001', name: 'IAM Director', role: 'iam_director', employmentType: 'fte', annualCost: 195000, fteEquivalent: 1.0, primaryPlatforms: ['SailPoint', 'CyberArk', 'Entra', 'Okta'], hoursPerWeek: 40, utilization: 85, createdAt: new Date().toISOString() },
  { personId: 'p-002', name: 'IAM Architect', role: 'iam_architect', employmentType: 'fte', annualCost: 175000, fteEquivalent: 1.0, primaryPlatforms: ['SailPoint', 'Entra'], hoursPerWeek: 40, utilization: 90, createdAt: new Date().toISOString() },
  { personId: 'p-003', name: 'IGA Lead Engineer', role: 'iga_specialist', employmentType: 'fte', annualCost: 155000, fteEquivalent: 1.0, primaryPlatforms: ['SailPoint'], hoursPerWeek: 40, utilization: 95, createdAt: new Date().toISOString() },
  { personId: 'p-004', name: 'PAM Engineer', role: 'pam_specialist', employmentType: 'fte', annualCost: 148000, fteEquivalent: 1.0, primaryPlatforms: ['CyberArk'], hoursPerWeek: 40, utilization: 90, createdAt: new Date().toISOString() },
  { personId: 'p-005', name: 'AM / Entra Engineer', role: 'am_specialist', employmentType: 'fte', annualCost: 142000, fteEquivalent: 1.0, primaryPlatforms: ['Entra'], hoursPerWeek: 40, utilization: 85, createdAt: new Date().toISOString() },
  { personId: 'p-006', name: 'CIAM Engineer', role: 'ciam_specialist', employmentType: 'fte', annualCost: 145000, fteEquivalent: 1.0, primaryPlatforms: ['Okta'], hoursPerWeek: 40, utilization: 80, createdAt: new Date().toISOString() },
  { personId: 'p-007', name: 'IAM Analyst', role: 'iam_analyst', employmentType: 'fte', annualCost: 110000, fteEquivalent: 1.0, primaryPlatforms: ['SailPoint', 'Entra'], hoursPerWeek: 40, utilization: 90, createdAt: new Date().toISOString() },
  { personId: 'p-008', name: 'IAM Analyst 2', role: 'iam_analyst', employmentType: 'fte', annualCost: 108000, fteEquivalent: 1.0, primaryPlatforms: ['SailPoint'], hoursPerWeek: 40, utilization: 85, createdAt: new Date().toISOString() },

  // US Contractors (via TechServ)
  { personId: 'p-009', name: 'CyberArk Contractor', role: 'pam_specialist', employmentType: 'contractor', vendorId: 'v-staffing-us', annualCost: 156000, fteEquivalent: 1.0, primaryPlatforms: ['CyberArk'], hoursPerWeek: 40, utilization: 100, createdAt: new Date().toISOString() },
  { personId: 'p-010', name: 'Entra Contractor', role: 'am_specialist', employmentType: 'contractor', vendorId: 'v-staffing-us', annualCost: 148000, fteEquivalent: 1.0, primaryPlatforms: ['Entra'], hoursPerWeek: 40, utilization: 100, createdAt: new Date().toISOString() },
  { personId: 'p-011', name: 'SailPoint Contractor', role: 'iga_specialist', employmentType: 'contractor', vendorId: 'v-staffing-us', annualCost: 146000, fteEquivalent: 1.0, primaryPlatforms: ['SailPoint'], hoursPerWeek: 40, utilization: 100, createdAt: new Date().toISOString() },

  // Offshore (via Infosys — 8 FTE equivalent at blended rate)
  { personId: 'p-012', name: 'Infosys IAM Ops Team (x8)', role: 'iam_analyst', employmentType: 'offshore', vendorId: 'v-infosys', annualCost: 320000, fteEquivalent: 8.0, primaryPlatforms: ['SailPoint', 'Entra'], hoursPerWeek: 40, utilization: 85, createdAt: new Date().toISOString() },
];
