import { BaseConnector } from './base';
import { ConnectorType } from '../types';

interface SailPointSource {
  id: string;
  name: string;
  type: string;
  connectorName: string;
  status: string;
}

interface SailPointRule {
  id?: string;
  name: string;
  type: 'AttributeGenerator' | 'Correlation' | 'Transformation' | 'BeforeProvisioning' | 'AfterProvisioning';
  language: 'beanshell' | 'xml';
  source: string;
  description?: string;
}

interface SailPointWorkflow {
  id?: string;
  name: string;
  type: string;
  steps: WorkflowStep[];
}

interface WorkflowStep {
  id: string;
  type: string;
  name: string;
  parameters?: Record<string, unknown>;
}

interface CertificationCampaign {
  name: string;
  description?: string;
  type: 'MANAGER' | 'SOURCE_OWNER' | 'SEARCH' | 'ROLE_COMPOSITION';
  deadline?: string;
}

export class SailPointConnector extends BaseConnector {
  readonly type: ConnectorType = 'sailpoint';

  protected get isConfigured(): boolean {
    return !!(
      process.env.SAILPOINT_BASE_URL &&
      process.env.SAILPOINT_CLIENT_ID &&
      process.env.SAILPOINT_CLIENT_SECRET
    );
  }

  /**
   * List all identity sources.
   * Live: GET {base}/v3/sources
   */
  async listSources(): Promise<SailPointSource[]> {
    if (!this.isConfigured) {
      return this.mockResponse<SailPointSource[]>([
        { id: 'src-001', name: 'Active Directory', type: 'DIRECT_CONNECT', connectorName: 'active-directory', status: 'SOURCE_STATE_HEALTHY' },
        { id: 'src-002', name: 'Salesforce', type: 'DIRECT_CONNECT', connectorName: 'salesforce', status: 'SOURCE_STATE_HEALTHY' },
        { id: 'src-003', name: 'SAP ERP', type: 'DIRECT_CONNECT', connectorName: 'sap', status: 'SOURCE_STATE_NEEDS_CONFIGURATION' },
      ]);
    }
    throw new Error('Live SailPoint API not yet implemented');
  }

  /**
   * Create a BeanShell or XML rule in SailPoint.
   * Live: POST {base}/v3/rules
   */
  async createRule(rule: SailPointRule): Promise<SailPointRule & { id: string }> {
    if (!this.isConfigured) {
      return this.mockResponse({ ...rule, id: `rule-mock-${Date.now()}` });
    }
    throw new Error('Live SailPoint API not yet implemented');
  }

  /**
   * Generate a BeanShell AttributeGenerator rule for a given app and attribute.
   * Returns the full rule source code ready for SailPoint import.
   */
  generateAttributeGeneratorRule(params: {
    appName: string;
    attribute: string;
    logic: string;
  }): SailPointRule {
    const source = `
import sailpoint.object.Identity;
import sailpoint.object.Application;
import org.apache.log4j.Logger;

Logger log = Logger.getLogger("rule.${params.appName}.${params.attribute}");

// Generated by idvize IAM Orchestration Platform
// Application: ${params.appName}
// Attribute: ${params.attribute}

Identity identity = (Identity) context.getObjectByName(Identity.class, identityName);

if (identity == null) {
  log.warn("Identity not found: " + identityName);
  return null;
}

// Custom logic
${params.logic}
`.trim();

    return {
      name: `${params.appName}_${params.attribute}_Generator`,
      type: 'AttributeGenerator',
      language: 'beanshell',
      source,
      description: `Auto-generated AttributeGenerator for ${params.appName} :: ${params.attribute}`,
    };
  }

  /**
   * Create an access certification campaign.
   * Live: POST {base}/v3/campaigns
   */
  async createCertificationCampaign(campaign: CertificationCampaign): Promise<{ id: string; activationDate: string }> {
    if (!this.isConfigured) {
      return this.mockResponse({
        id: `campaign-mock-${Date.now()}`,
        activationDate: new Date().toISOString(),
      });
    }
    throw new Error('Live SailPoint API not yet implemented');
  }

  /**
   * Create a lifecycle state workflow.
   * Live: POST {base}/v3/workflows
   */
  async createWorkflow(workflow: SailPointWorkflow): Promise<SailPointWorkflow & { id: string }> {
    if (!this.isConfigured) {
      return this.mockResponse({ ...workflow, id: `wf-mock-${Date.now()}` });
    }
    throw new Error('Live SailPoint API not yet implemented');
  }

  /**
   * Trigger a manual provisioning action for an identity.
   * Live: POST {base}/v3/manual-work-items
   */
  async triggerProvisioning(identityId: string, appId: string, action: 'Add_Account' | 'Remove_Account' | 'Modify_Account'): Promise<{ taskId: string }> {
    if (!this.isConfigured) {
      return this.mockResponse({ taskId: `task-mock-${Date.now()}` });
    }
    throw new Error('Live SailPoint API not yet implemented');
  }
}

export const sailpointConnector = new SailPointConnector();
