/**
 * IDVIZE IAM OS — Comprehensive Controls Catalog
 *
 * All IAM controls sourced from industry frameworks and categorised
 * across the four IAM pillars: AM · IGA · PAM · CIAM
 *
 * Sources: NIST SP 800-53, ISO 27001, SOX, PCI-DSS, HIPAA, CIS Controls,
 *          ISACA COBIT, SailPoint / Okta / CyberArk reference architectures
 */

export type IamPillar = 'AM' | 'IGA' | 'PAM' | 'CIAM';
export type ControlComplexity = 'low' | 'medium' | 'high';
export type ControlRiskReduction = 'critical' | 'high' | 'medium' | 'low';

export interface CatalogControl {
  controlId: string;
  name: string;
  pillar: IamPillar;
  category: string;
  description: string;
  capabilities: string[];
  riskReduction: ControlRiskReduction;
  applicableTiers: ('critical' | 'high' | 'medium' | 'low')[];
  policyDrivers: string[];
  implementationComplexity: ControlComplexity;
  tags: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// AM — Access Management
// ─────────────────────────────────────────────────────────────────────────────
const AM_CONTROLS: CatalogControl[] = [
  {
    controlId: 'AM-001',
    name: 'Single Sign-On (SSO)',
    pillar: 'AM',
    category: 'Authentication',
    description: 'Centralise authentication so users log in once and gain access to all authorised applications without re-authenticating.',
    capabilities: ['SSO Federation Protocols', 'Identity Brokering', 'Cross-Domain Authentication', 'Token-Based Sessions'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['SOX', 'NIST SP 800-53', 'ISO 27001', 'PCI-DSS'],
    implementationComplexity: 'medium',
    tags: ['sso', 'authentication', 'federation'],
  },
  {
    controlId: 'AM-002',
    name: 'Multi-Factor Authentication (MFA)',
    pillar: 'AM',
    category: 'Authentication',
    description: 'Require two or more verification factors before granting access, reducing the risk of compromised credentials.',
    capabilities: ['OTP / TOTP', 'Push Notifications', 'Hardware Tokens', 'Biometric Verification', 'Passkeys'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high', 'medium', 'low'],
    policyDrivers: ['NIST SP 800-63B', 'PCI-DSS', 'HIPAA', 'SOX', 'Zero Trust'],
    implementationComplexity: 'low',
    tags: ['mfa', 'authentication', 'zero-trust'],
  },
  {
    controlId: 'AM-003',
    name: 'Passwordless Authentication',
    pillar: 'AM',
    category: 'Authentication',
    description: 'Eliminate passwords by using passkeys, biometrics, or hardware tokens — removing the largest credential attack surface.',
    capabilities: ['Passkeys (FIDO2/WebAuthn)', 'Biometric Authentication', 'Magic Links', 'Certificate-Based Auth'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['NIST SP 800-63B', 'Zero Trust', 'FIDO Alliance'],
    implementationComplexity: 'high',
    tags: ['passwordless', 'passkeys', 'biometrics', 'fido2'],
  },
  {
    controlId: 'AM-004',
    name: 'Adaptive Authentication',
    pillar: 'AM',
    category: 'Authentication',
    description: 'Dynamically adjust authentication requirements based on risk signals: location, device, behaviour, and time-of-access.',
    capabilities: ['Risk-Based Authentication', 'Contextual Access Policies', 'Anomaly Detection', 'Step-Up Authentication'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['Zero Trust', 'NIST SP 800-53', 'ISO 27001'],
    implementationComplexity: 'high',
    tags: ['adaptive', 'risk-based', 'contextual'],
  },
  {
    controlId: 'AM-005',
    name: 'Role-Based Access Control (RBAC)',
    pillar: 'AM',
    category: 'Authorization',
    description: 'Grant access based on a user\'s role within the organisation; each role has a defined set of permissions aligned to job function.',
    capabilities: ['Role Definition & Assignment', 'Permission Mapping', 'Least Privilege Enforcement', 'Role Hierarchy Management'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high', 'medium', 'low'],
    policyDrivers: ['SOX', 'NIST SP 800-53', 'ISO 27001', 'PCI-DSS', 'HIPAA'],
    implementationComplexity: 'medium',
    tags: ['rbac', 'authorization', 'least-privilege'],
  },
  {
    controlId: 'AM-006',
    name: 'Attribute-Based Access Control (ABAC)',
    pillar: 'AM',
    category: 'Authorization',
    description: 'Make access decisions based on attributes of users, resources, and environment — enabling fine-grained, dynamic authorisation.',
    capabilities: ['Policy Engine', 'Attribute Evaluation', 'Dynamic Access Decisions', 'XACML / OPA Support'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['NIST SP 800-162', 'Zero Trust', 'GDPR'],
    implementationComplexity: 'high',
    tags: ['abac', 'authorization', 'dynamic-access', 'policy-engine'],
  },
  {
    controlId: 'AM-007',
    name: 'Policy-Based Access Control (PBAC)',
    pillar: 'AM',
    category: 'Authorization',
    description: 'Define and enforce centralised access policies that evaluate multiple conditions (role, attribute, context, risk) at runtime.',
    capabilities: ['Centralised Policy Store', 'Policy Evaluation Engine', 'Runtime Enforcement', 'Policy Versioning'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['NIST SP 800-53', 'Zero Trust', 'ISO 27001'],
    implementationComplexity: 'high',
    tags: ['pbac', 'policy-engine', 'authorization'],
  },
  {
    controlId: 'AM-008',
    name: 'Entitlement Management',
    pillar: 'AM',
    category: 'Authorization',
    description: 'Manage, track, and enforce the full set of permissions and entitlements granted to each identity across all systems.',
    capabilities: ['Entitlement Discovery', 'Entitlement Catalog', 'Over-Provisioning Detection', 'Fine-Grained Permissions'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['SOX', 'PCI-DSS', 'NIST SP 800-53'],
    implementationComplexity: 'medium',
    tags: ['entitlements', 'permissions', 'fine-grained'],
  },
  {
    controlId: 'AM-009',
    name: 'Dynamic Access Controls',
    pillar: 'AM',
    category: 'Authorization',
    description: 'Adjust access rights in real time based on changing context, risk score, or environmental signals — no manual intervention required.',
    capabilities: ['Real-Time Policy Evaluation', 'Context-Aware Enforcement', 'Automated Revocation', 'Session Risk Monitoring'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['Zero Trust', 'NIST SP 800-207'],
    implementationComplexity: 'high',
    tags: ['dynamic', 'real-time', 'zero-trust'],
  },
  {
    controlId: 'AM-010',
    name: 'Federated Identity Management',
    pillar: 'AM',
    category: 'Federation',
    description: 'Enable trusted identity federation across organisational and domain boundaries using open standards.',
    capabilities: ['SAML 2.0', 'OAuth 2.0 / OIDC', 'Identity Brokering Platforms', 'Cross-Domain Authentication', 'Trust Framework Management'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['ISO 27001', 'NIST SP 800-63C', 'GDPR'],
    implementationComplexity: 'medium',
    tags: ['federation', 'saml', 'oauth', 'oidc'],
  },
  {
    controlId: 'AM-011',
    name: 'API Security & Token Management',
    pillar: 'AM',
    category: 'API Security',
    description: 'Secure API access through OAuth 2.0 tokens, API keys, and gateway enforcement — preventing unauthorised programmatic access.',
    capabilities: ['OAuth 2.0 Token Issuance', 'API Key Management', 'Token Rotation & Expiry', 'API Gateway Integration', 'JWT Validation'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['OWASP API Top 10', 'PCI-DSS', 'NIST SP 800-53'],
    implementationComplexity: 'medium',
    tags: ['api', 'token', 'oauth', 'jwt'],
  },
  {
    controlId: 'AM-012',
    name: 'Zero Trust Security Model',
    pillar: 'AM',
    category: 'Architecture',
    description: 'Never trust, always verify. Enforce continuous authentication and authorisation for every access request regardless of network location.',
    capabilities: ['Continuous Verification', 'Least Privilege Access', 'Micro-Segmentation', 'Device Trust', 'Identity-Centric Security'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['NIST SP 800-207', 'Zero Trust', 'CISA ZTA', 'Executive Order 14028'],
    implementationComplexity: 'high',
    tags: ['zero-trust', 'continuous-verification', 'architecture'],
  },
  {
    controlId: 'AM-013',
    name: 'Conditional Access',
    pillar: 'AM',
    category: 'Authorization',
    description: 'Control access based on conditions: user location, device compliance, time of day, MFA status, and network.',
    capabilities: ['Location-Based Policies', 'Device Compliance Checks', 'Time-Based Restrictions', 'Network-Based Controls', 'MFA Step-Up'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['Zero Trust', 'NIST SP 800-53', 'ISO 27001'],
    implementationComplexity: 'medium',
    tags: ['conditional-access', 'context', 'policy'],
  },
  {
    controlId: 'AM-014',
    name: 'Temporary & Session-Based Access',
    pillar: 'AM',
    category: 'Authorization',
    description: 'Issue time-limited access grants and session tokens that auto-expire, eliminating standing permissions and permanent keys.',
    capabilities: ['Time-Limited Tokens', 'Session Expiry Controls', 'Temporary Role Assignment', 'Ephemeral Credentials'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['Zero Trust', 'NIST SP 800-53', 'PCI-DSS'],
    implementationComplexity: 'medium',
    tags: ['temporary-access', 'session', 'ephemeral'],
  },
  {
    controlId: 'AM-015',
    name: 'SaaS & Hybrid Cloud IAM',
    pillar: 'AM',
    category: 'Cloud Security',
    description: 'Extend IAM controls consistently across SaaS, IaaS, PaaS, and hybrid cloud environments with centralised identity governance.',
    capabilities: ['Cloud-Native IAM Integration', 'Multi-Cloud Identity Federation', 'SaaS App Governance', 'Cloud Entitlement Management'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['CSA Cloud Controls Matrix', 'ISO 27017', 'NIST SP 800-53'],
    implementationComplexity: 'high',
    tags: ['cloud', 'saas', 'hybrid', 'multi-cloud'],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// IGA — Identity Governance & Administration
// ─────────────────────────────────────────────────────────────────────────────
const IGA_CONTROLS: CatalogControl[] = [
  {
    controlId: 'IGA-001',
    name: 'Identity Lifecycle Management (JML)',
    pillar: 'IGA',
    category: 'Lifecycle',
    description: 'Govern the full identity lifecycle: Joiner onboarding, Mover role changes, and Leaver de-provisioning — ensuring no orphaned accounts.',
    capabilities: ['Automated Onboarding', 'Role-Change Workflows', 'Automated De-Provisioning', 'Orphan Account Prevention', 'HR System Integration'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high', 'medium', 'low'],
    policyDrivers: ['SOX', 'ISO 27001', 'NIST SP 800-53', 'PCI-DSS', 'HIPAA'],
    implementationComplexity: 'high',
    tags: ['jml', 'lifecycle', 'provisioning', 'joiner-mover-leaver'],
  },
  {
    controlId: 'IGA-002',
    name: 'User Provisioning & De-Provisioning',
    pillar: 'IGA',
    category: 'Provisioning',
    description: 'Automate account creation, modification, and removal across all connected systems based on HR events and policy triggers.',
    capabilities: ['SCIM 2.0 Provisioning', 'Automated Account Creation', 'Profile Synchronisation', 'Termination Workflows', 'Multi-System Propagation'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high', 'medium', 'low'],
    policyDrivers: ['SOX', 'NIST SP 800-53', 'ISO 27001', 'PCI-DSS'],
    implementationComplexity: 'medium',
    tags: ['provisioning', 'scim', 'deprovisioning', 'automation'],
  },
  {
    controlId: 'IGA-003',
    name: 'Role-Based Provisioning',
    pillar: 'IGA',
    category: 'Provisioning',
    description: 'Automatically provision accounts and entitlements based on job role, department, and organisational context.',
    capabilities: ['Role-to-Entitlement Mapping', 'Automatic Provisioning on Role Assignment', 'Role Catalog Management', 'Department-Based Rules'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['SOX', 'NIST SP 800-53', 'ISO 27001'],
    implementationComplexity: 'medium',
    tags: ['rbac', 'provisioning', 'role-based'],
  },
  {
    controlId: 'IGA-004',
    name: 'Just-In-Time (JIT) Provisioning',
    pillar: 'IGA',
    category: 'Provisioning',
    description: 'Provision accounts and access on demand at the point of first authentication, eliminating pre-created standing accounts.',
    capabilities: ['On-Demand Account Creation', 'SAML / OIDC JIT', 'Attribute-Driven Provisioning', 'Temporary Account Lifecycle'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['Zero Trust', 'NIST SP 800-53'],
    implementationComplexity: 'medium',
    tags: ['jit', 'provisioning', 'on-demand'],
  },
  {
    controlId: 'IGA-005',
    name: 'Access Review & Certification',
    pillar: 'IGA',
    category: 'Governance',
    description: 'Periodically certify that users still require their current access rights; revoke access that is no longer needed.',
    capabilities: ['Scheduled Access Campaigns', 'Manager-Led Reviews', 'Automated Revocation', 'Audit Trail of Decisions', 'Risk-Based Review Prioritisation'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['SOX', 'PCI-DSS', 'HIPAA', 'ISO 27001', 'NIST SP 800-53'],
    implementationComplexity: 'medium',
    tags: ['access-review', 'certification', 'attestation', 'governance'],
  },
  {
    controlId: 'IGA-006',
    name: 'Segregation of Duties (SoD)',
    pillar: 'IGA',
    category: 'Governance',
    description: 'Detect and prevent toxic combinations of access rights that would allow a single user to initiate and approve the same transaction.',
    capabilities: ['SoD Policy Definition', 'Conflict Detection Engine', 'Real-Time Violation Alerts', 'Compensating Controls', 'SoD Reporting'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['SOX', 'PCI-DSS', 'ISO 27001', 'NIST SP 800-53'],
    implementationComplexity: 'high',
    tags: ['sod', 'separation-of-duties', 'fraud-prevention', 'compliance'],
  },
  {
    controlId: 'IGA-007',
    name: 'Role Mining & Optimisation',
    pillar: 'IGA',
    category: 'Governance',
    description: 'Analyse existing access patterns to discover natural role groupings, eliminate role explosion, and align roles to business functions.',
    capabilities: ['Access Pattern Analysis', 'Role Discovery Algorithms', 'Role Consolidation', 'Outlier Detection', 'Business Role Alignment'],
    riskReduction: 'medium',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['SOX', 'ISO 27001'],
    implementationComplexity: 'high',
    tags: ['role-mining', 'optimisation', 'analytics'],
  },
  {
    controlId: 'IGA-008',
    name: 'Self-Service Access Requests',
    pillar: 'IGA',
    category: 'Workflow',
    description: 'Allow users to request additional access through a governed self-service portal, replacing IT tickets with structured approval workflows.',
    capabilities: ['Access Request Portal', 'Application Catalog', 'Approval Routing', 'Request Tracking', 'Delegation Support'],
    riskReduction: 'medium',
    applicableTiers: ['critical', 'high', 'medium', 'low'],
    policyDrivers: ['ISO 27001', 'NIST SP 800-53'],
    implementationComplexity: 'medium',
    tags: ['self-service', 'access-request', 'workflow'],
  },
  {
    controlId: 'IGA-009',
    name: 'Access Approval Workflows',
    pillar: 'IGA',
    category: 'Workflow',
    description: 'Route access requests through multi-level approval chains based on risk, application, and organisational policy.',
    capabilities: ['Multi-Level Approvals', 'Escalation Rules', 'Time-Based Auto-Approval/Rejection', 'Approval Audit Trail', 'Risk-Weighted Routing'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['SOX', 'ISO 27001', 'NIST SP 800-53'],
    implementationComplexity: 'medium',
    tags: ['approval', 'workflow', 'governance'],
  },
  {
    controlId: 'IGA-010',
    name: 'Certification & Attestation',
    pillar: 'IGA',
    category: 'Governance',
    description: 'Formally attest that access assignments are correct and compliant; provide auditors with evidence of regular review cycles.',
    capabilities: ['Automated Campaign Scheduling', 'Role & Entitlement Attestation', 'Risk-Based Prioritisation', 'Audit-Ready Reports', 'Compliance Evidence Packages'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['SOX', 'PCI-DSS', 'HIPAA', 'ISO 27001', 'GDPR'],
    implementationComplexity: 'medium',
    tags: ['attestation', 'certification', 'compliance', 'audit'],
  },
  {
    controlId: 'IGA-011',
    name: 'Password Management & Policy',
    pillar: 'IGA',
    category: 'Credential Governance',
    description: 'Enforce strong password policies, enable self-service resets, and prevent credential reuse to reduce password-based attacks.',
    capabilities: ['Password Complexity Enforcement', 'Self-Service Password Reset (SSPR)', 'Password History & Reuse Prevention', 'Breach Detection Integration'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high', 'medium', 'low'],
    policyDrivers: ['NIST SP 800-63B', 'ISO 27001', 'PCI-DSS'],
    implementationComplexity: 'low',
    tags: ['password', 'sspr', 'credential-policy'],
  },
  {
    controlId: 'IGA-012',
    name: 'Audit & Compliance Reporting',
    pillar: 'IGA',
    category: 'Compliance',
    description: 'Continuously track all identity and access events, maintain tamper-evident audit logs, and generate regulatory compliance reports.',
    capabilities: ['Centralised Audit Log', 'Immutable Event Store', 'Regulatory Report Templates', 'Real-Time Compliance Dashboards', 'Evidence Export'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['SOX', 'PCI-DSS', 'HIPAA', 'GDPR', 'ISO 27001', 'NIST SP 800-53'],
    implementationComplexity: 'medium',
    tags: ['audit', 'compliance', 'reporting', 'logging'],
  },
  {
    controlId: 'IGA-013',
    name: 'AI-Powered Identity Governance',
    pillar: 'IGA',
    category: 'Intelligence',
    description: 'Apply machine learning to automate lifecycle decisions, detect anomalous access patterns, and recommend access changes.',
    capabilities: ['ML-Based Access Recommendations', 'Anomaly Detection', 'Automated Policy Decisions', 'Outlier Identification', 'Predictive Governance'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['Zero Trust', 'NIST SP 800-53'],
    implementationComplexity: 'high',
    tags: ['ai', 'ml', 'intelligent-governance', 'automation'],
  },
  {
    controlId: 'IGA-014',
    name: 'User Entitlement Reporting',
    pillar: 'IGA',
    category: 'Reporting',
    description: 'Provide a complete, queryable view of every entitlement held by every identity — essential for audits and access reviews.',
    capabilities: ['Entitlement Inventory', 'User-Centric Access View', 'Cross-System Aggregation', 'Exportable Reports', 'Drill-Down Analytics'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['SOX', 'PCI-DSS', 'ISO 27001'],
    implementationComplexity: 'medium',
    tags: ['entitlement', 'reporting', 'visibility'],
  },
  {
    controlId: 'IGA-015',
    name: 'Policy Enforcement & Risk Reporting',
    pillar: 'IGA',
    category: 'Governance',
    description: 'Continuously evaluate access against defined policies, surface policy violations, and generate risk-based compliance reports.',
    capabilities: ['Policy Violation Detection', 'Risk Scoring', 'Compliance Score Tracking', 'Remediation Workflows', 'Executive Risk Dashboards'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['SOX', 'ISO 27001', 'NIST SP 800-53', 'COBIT'],
    implementationComplexity: 'medium',
    tags: ['policy', 'risk', 'compliance', 'enforcement'],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// PAM — Privileged Access Management
// ─────────────────────────────────────────────────────────────────────────────
const PAM_CONTROLS: CatalogControl[] = [
  {
    controlId: 'PAM-001',
    name: 'Privileged Account & Session Management',
    pillar: 'PAM',
    category: 'Privileged Access',
    description: 'Discover, onboard, and govern all privileged accounts (admin, root, superuser) with full session recording and audit trails.',
    capabilities: ['Privileged Account Discovery', 'Session Initiation Control', 'Full Session Recording', 'Live Session Monitoring', 'Session Termination'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['PCI-DSS', 'SOX', 'HIPAA', 'NIST SP 800-53', 'ISO 27001'],
    implementationComplexity: 'high',
    tags: ['pam', 'privileged', 'session-management', 'recording'],
  },
  {
    controlId: 'PAM-002',
    name: 'Privileged Credential Vault',
    pillar: 'PAM',
    category: 'Credential Governance',
    description: 'Centralise storage of all privileged credentials in an encrypted, access-controlled vault with automated rotation.',
    capabilities: ['Encrypted Credential Store', 'Automated Password Rotation', 'Check-Out / Check-In Workflow', 'Shared Account Management', 'Vault API'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['PCI-DSS', 'SOX', 'HIPAA', 'NIST SP 800-53', 'CIS Controls'],
    implementationComplexity: 'medium',
    tags: ['vault', 'password-vaulting', 'credential', 'rotation'],
  },
  {
    controlId: 'PAM-003',
    name: 'Just-In-Time (JIT) Privileged Access',
    pillar: 'PAM',
    category: 'Privileged Access',
    description: 'Grant elevated privileges only when needed, for a limited duration, and revoke them automatically — eliminating standing admin access.',
    capabilities: ['On-Demand Privilege Elevation', 'Time-Bound Access Windows', 'Approval-Gated Elevation', 'Automatic Revocation', 'Audit Trail'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['Zero Trust', 'PCI-DSS', 'NIST SP 800-53', 'ISO 27001'],
    implementationComplexity: 'high',
    tags: ['jit', 'privileged', 'zero-standing-privilege'],
  },
  {
    controlId: 'PAM-004',
    name: 'Privileged Session Monitoring & Recording',
    pillar: 'PAM',
    category: 'Monitoring',
    description: 'Record, monitor, and analyse all privileged sessions in real time — detect and alert on suspicious privileged behaviour.',
    capabilities: ['Video-Quality Session Recording', 'Keystroke Logging', 'Real-Time Anomaly Alerts', 'Session Replay', 'OCR-Based Search'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['PCI-DSS', 'SOX', 'HIPAA', 'ISO 27001'],
    implementationComplexity: 'medium',
    tags: ['session-recording', 'monitoring', 'keystroke', 'forensics'],
  },
  {
    controlId: 'PAM-005',
    name: 'Least Privilege for Privileged Accounts',
    pillar: 'PAM',
    category: 'Privileged Access',
    description: 'Ensure privileged users only hold the minimum elevated permissions required for their tasks; no blanket admin rights.',
    capabilities: ['Privilege Discovery', 'Just-Enough-Administration (JEA)', 'Privilege Reduction', 'Application-Level Least Privilege', 'Delegation Controls'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['Zero Trust', 'NIST SP 800-53', 'PCI-DSS', 'CIS Controls'],
    implementationComplexity: 'high',
    tags: ['least-privilege', 'jea', 'privilege-reduction'],
  },
  {
    controlId: 'PAM-006',
    name: 'Remote Access Management',
    pillar: 'PAM',
    category: 'Privileged Access',
    description: 'Secure privileged remote access for vendors, contractors, and remote admins — no VPN credentials or direct network access required.',
    capabilities: ['Vendor Privileged Access', 'Agentless Remote Sessions', 'Browser-Based Access', 'Session Isolation', 'Access Request Workflow'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['PCI-DSS', 'SOX', 'ISO 27001'],
    implementationComplexity: 'medium',
    tags: ['remote-access', 'vendor-access', 'third-party'],
  },
  {
    controlId: 'PAM-007',
    name: 'Privileged Threat Detection',
    pillar: 'PAM',
    category: 'Threat Intelligence',
    description: 'Detect insider threats, account takeovers, and lateral movement by analysing privileged access behaviour with ML/UEBA.',
    capabilities: ['User & Entity Behaviour Analytics (UEBA)', 'Insider Threat Detection', 'Lateral Movement Detection', 'Automated Threat Response', 'Risk Scoring'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['NIST SP 800-53', 'ISO 27001', 'Zero Trust'],
    implementationComplexity: 'high',
    tags: ['threat-detection', 'ueba', 'insider-threat', 'ml'],
  },
  {
    controlId: 'PAM-008',
    name: 'Cryptographic Key Management',
    pillar: 'PAM',
    category: 'Key & Secrets Management',
    description: 'Generate, store, rotate, and retire cryptographic keys with enforced key lifecycle policies and HSM-backed security.',
    capabilities: ['Key Generation (HSM-backed)', 'Secure Key Storage', 'Automated Key Rotation', 'Key Usage Controls', 'Key Lifecycle Policy', 'PKCS#11 / KMIP Support'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['PCI-DSS', 'FIPS 140-2', 'NIST SP 800-57', 'ISO 27001'],
    implementationComplexity: 'high',
    tags: ['key-management', 'cryptography', 'hsm', 'encryption'],
  },
  {
    controlId: 'PAM-009',
    name: 'Secrets Management',
    pillar: 'PAM',
    category: 'Key & Secrets Management',
    description: 'Securely store, distribute, rotate, and monitor application secrets — passwords, API keys, tokens, and certificates — at scale.',
    capabilities: ['Secrets Vault (HashiCorp/CyberArk)', 'Dynamic Secrets Generation', 'Secret Distribution to Apps', 'Automated Secret Rotation', 'Secret Access Audit', 'Leak Prevention'],
    riskReduction: 'critical',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['PCI-DSS', 'SOX', 'NIST SP 800-53', 'ISO 27001'],
    implementationComplexity: 'medium',
    tags: ['secrets', 'vault', 'api-keys', 'rotation'],
  },
  {
    controlId: 'PAM-010',
    name: 'PAM Audit & Compliance',
    pillar: 'PAM',
    category: 'Compliance',
    description: 'Capture complete audit trails of all privileged activity and generate compliance evidence for PCI-DSS, SOX, and HIPAA audits.',
    capabilities: ['Privileged Activity Audit Log', 'Compliance Report Generation', 'Audit Evidence Packages', 'Real-Time Compliance Dashboards', 'Regulatory Mapping'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['PCI-DSS', 'SOX', 'HIPAA', 'ISO 27001'],
    implementationComplexity: 'medium',
    tags: ['audit', 'compliance', 'evidence', 'reporting'],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// CIAM — Customer Identity & Access Management
// ─────────────────────────────────────────────────────────────────────────────
const CIAM_CONTROLS: CatalogControl[] = [
  {
    controlId: 'CIAM-001',
    name: 'Customer Registration & Onboarding',
    pillar: 'CIAM',
    category: 'Customer Lifecycle',
    description: 'Provide a frictionless, brand-consistent registration experience with progressive profiling and identity verification.',
    capabilities: ['Self-Registration Flows', 'Progressive Profiling', 'Email / Phone Verification', 'Identity Proofing', 'Consent Capture'],
    riskReduction: 'medium',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['GDPR', 'CCPA', 'ISO 27001'],
    implementationComplexity: 'medium',
    tags: ['ciam', 'registration', 'onboarding', 'customer'],
  },
  {
    controlId: 'CIAM-002',
    name: 'Social Login & Identity Federation',
    pillar: 'CIAM',
    category: 'Authentication',
    description: 'Allow customers to authenticate using their existing social or enterprise identities (Google, Apple, LinkedIn, Microsoft).',
    capabilities: ['Social IdP Integration', 'OAuth 2.0 / OIDC', 'Account Linking', 'Cross-Domain SSO', 'Profile Sync from IdP'],
    riskReduction: 'medium',
    applicableTiers: ['high', 'medium', 'low'],
    policyDrivers: ['GDPR', 'CCPA'],
    implementationComplexity: 'low',
    tags: ['social-login', 'federation', 'oauth', 'customer'],
  },
  {
    controlId: 'CIAM-003',
    name: 'Customer MFA & Passwordless',
    pillar: 'CIAM',
    category: 'Authentication',
    description: 'Offer customers strong, low-friction authentication options including biometrics, passkeys, and magic links.',
    capabilities: ['Passkeys (FIDO2)', 'Biometric Authentication', 'Magic Link / OTP', 'Adaptive MFA for Consumers', 'SMS / Email OTP'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['GDPR', 'PSD2', 'NIST SP 800-63B'],
    implementationComplexity: 'medium',
    tags: ['mfa', 'passwordless', 'passkeys', 'biometrics', 'customer'],
  },
  {
    controlId: 'CIAM-004',
    name: 'Self-Service Access Request Portal',
    pillar: 'CIAM',
    category: 'Self-Service',
    description: 'Empower customers and partners to request, manage, and revoke their own access through a governed self-service portal.',
    capabilities: ['Access Request UI', 'Service Catalog', 'Approval Routing', 'Request Status Tracking', 'Delegated Administration'],
    riskReduction: 'medium',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['ISO 27001', 'GDPR'],
    implementationComplexity: 'medium',
    tags: ['self-service', 'portal', 'customer'],
  },
  {
    controlId: 'CIAM-005',
    name: 'Delegated Administration',
    pillar: 'CIAM',
    category: 'Administration',
    description: 'Allow trusted customer admins or partners to manage sub-accounts and access within their own organisation boundary.',
    capabilities: ['Tenant Admin Delegation', 'Scoped Permission Grant', 'B2B Partner Management', 'Invitation Workflows', 'Admin Audit Trail'],
    riskReduction: 'medium',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['ISO 27001', 'GDPR'],
    implementationComplexity: 'medium',
    tags: ['delegation', 'b2b', 'partner', 'tenant-admin'],
  },
  {
    controlId: 'CIAM-006',
    name: 'Consent & Privacy Management',
    pillar: 'CIAM',
    category: 'Privacy',
    description: 'Capture, store, and honour customer consent preferences; provide data access and deletion capabilities for privacy compliance.',
    capabilities: ['Consent Collection & Storage', 'Granular Preference Centre', 'Right to Access (DSAR)', 'Right to Erasure', 'Consent Audit Trail'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high', 'medium'],
    policyDrivers: ['GDPR', 'CCPA', 'LGPD', 'ISO 27701'],
    implementationComplexity: 'medium',
    tags: ['consent', 'privacy', 'gdpr', 'dsar'],
  },
  {
    controlId: 'CIAM-007',
    name: 'Automated Access Fulfilment',
    pillar: 'CIAM',
    category: 'Workflow',
    description: 'Automatically fulfil access requests for low-risk resources based on policy, removing manual bottlenecks for customer-facing access.',
    capabilities: ['Policy-Based Auto-Approval', 'Entitlement Auto-Provisioning', 'Real-Time Fulfilment', 'Escalation for High-Risk Requests'],
    riskReduction: 'medium',
    applicableTiers: ['high', 'medium', 'low'],
    policyDrivers: ['ISO 27001'],
    implementationComplexity: 'medium',
    tags: ['automation', 'fulfilment', 'workflow'],
  },
  {
    controlId: 'CIAM-008',
    name: 'Customer Risk & Fraud Detection',
    pillar: 'CIAM',
    category: 'Risk Intelligence',
    description: 'Detect account takeover attempts, fraudulent registrations, and suspicious customer behaviour in real time.',
    capabilities: ['Device Fingerprinting', 'Bot Detection', 'Account Takeover Detection', 'Risk-Based Authentication Triggers', 'Fraud Scoring'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['PSD2', 'GDPR', 'NIST SP 800-53'],
    implementationComplexity: 'high',
    tags: ['fraud', 'risk', 'bot-detection', 'ato'],
  },
  {
    controlId: 'CIAM-009',
    name: 'B2B Identity & Partner Access',
    pillar: 'CIAM',
    category: 'Federation',
    description: 'Manage business-to-business identity federation, enabling partner organisations to use their own IdP while accessing your services.',
    capabilities: ['B2B Federation (SAML/OIDC)', 'Organisation-Level Onboarding', 'Partner SSO', 'Trust Hierarchy Management', 'B2B Audit Logs'],
    riskReduction: 'high',
    applicableTiers: ['critical', 'high'],
    policyDrivers: ['ISO 27001', 'GDPR'],
    implementationComplexity: 'high',
    tags: ['b2b', 'partner', 'federation', 'saml'],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Full catalog
// ─────────────────────────────────────────────────────────────────────────────
export const CONTROLS_CATALOG: CatalogControl[] = [
  ...AM_CONTROLS,
  ...IGA_CONTROLS,
  ...PAM_CONTROLS,
  ...CIAM_CONTROLS,
];

export const CATALOG_SUMMARY = {
  total:    CONTROLS_CATALOG.length,
  byPillar: {
    AM:   AM_CONTROLS.length,
    IGA:  IGA_CONTROLS.length,
    PAM:  PAM_CONTROLS.length,
    CIAM: CIAM_CONTROLS.length,
  },
  byRiskReduction: {
    critical: CONTROLS_CATALOG.filter(c => c.riskReduction === 'critical').length,
    high:     CONTROLS_CATALOG.filter(c => c.riskReduction === 'high').length,
    medium:   CONTROLS_CATALOG.filter(c => c.riskReduction === 'medium').length,
    low:      CONTROLS_CATALOG.filter(c => c.riskReduction === 'low').length,
  },
};
